name: era5_hp_3d
n_trials: 8

pruner:
  n_startup_trials: 5
  n_warmup_steps: 10
  n_min_trials: 5

params:
  batch_size:
    type: categorical
    choices:
      - 8
      - 16
      - 32
      - 64

  lr:
    type: float
    low: 1e-5
    high: 1e-2
    log: true

  weight_decay:
    type: float
    low: 1e-6
    high: 1e-2
    log: true
