name: era5_hp_3d_3
n_trials: 4

pruner:
  n_startup_trials: 15
  n_warmup_steps: 20
  n_min_trials: 10

params:
  batch_size:
    type: categorical
    choices:
      - 16
      - 32
      - 64

  lr:
    type: float
    low: 1e-5
    high: 1e-2
    log: true

  weight_decay:
    type: float
    low: 1e-6
    high: 1e-2
    log: true
