name: fluid_data
path: ./data/darcy/
use_double: False
time_series: False
validation_metrics: ['mse', 'darcy']
test_metrics: [mse]
dims:
  x: 64
  y: 64
  z: 2
  input_dims: 2
  output_dims: 2
train: true
