name: era5
path: ./data/era5/zarr/
use_double: False
time_series: True
validation_metrics: ['mse', 'era5_vorticity']
test_metrics: [mse]
dims:
  x: 480
  y: 32
  input_dims: 53
  output_dims: 15
train: true
atmospheric_features:
  - 'u'
  - 'v'
  - 'pv'
  - 't'
  - 'z'

single_features: []
static_features: []
max_year: 2025
time_step: 1

"lon_range": null # Data is full range
"lat_range": null # Already subsampled to [70, 46]
"downsample_factor": 3
