defaults:
  - experiment: exp1
  - dataset: darcy
  - scheduler: ddpm
  - _self_

wandb: False #Avoid logging to wandb
k_folds: null #if null no cross-val, else give number of folds
idx_fold: null
seed: 42

loss:
  name: darcy

model:
  name: unet2d
  save_best_model: true
  save_dir: './models'
  id: null
  x0_pred: 'mean'
  monitor: val_loss
  mode: min
  dims:
    x: 64
    y: 64
    z: 2
    input_dims: 2
    output_dims: 2

# Avoid logging to folders
hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: False
  sweep:
    dir: .
