defaults:
  - experiment: exp1
  - dataset: era5
  - scheduler: ddpm
  - hp_study: null
  - _self_

wandb: False #Avoid logging to wandb
k_folds: null #if null no cross-val, else give number of folds
idx_fold: null
seed: 42
id: null
save_dir: 'models/'

loss:
  name: mse
  c_residual: 1e-1 #[vorticity loss (#1 planetary, #2 geostrophic wind, #3 qgpv)]

model:
  name: unet2d_conditional
  save_best_model: true
  dims: null
  ckpt_path: null

# Avoid logging to folders
hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: False
  sweep:
    dir: .
