defaults:
  - experiment: exp1
  - dataset: cifar10
  - scheduler: ddpm
  - _self_

wandb: False #Avoid logging to wandb
k_folds: null #if null no cross-val, else give number of folds
idx_fold: null
seed: 42
id: null
save_dir: 'models/'

loss:
  name: mse
  c_residual: 1e-3

model:
  name: unet2d
  save_best_model: true
  dims: null

# Avoid logging to folders
hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: False
  sweep:
    dir: .
