model:
  path: models/exp1-eval_test

steps: 5

dataset:
  type: test
  path: ./data/era5/zarr_test


# Avoid logging to folders
hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: False
  sweep:
    dir: .
